namespace LedgerNest.Desktop;

// Choices copied from the legacy country and currency catalogs.
public static class LegacyChoices
{
    public static readonly string[] Countries = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo (Brazzaville)",
        "Congo (Kinshasa)",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Korea",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe",
    ];
    public static readonly string[] Currencies = [
        "Rs. INR — Indian Rupee",
        "AED. AED — UAE Dirham",
        "؋ AFN — Afghan Afghani",
        "Lek ALL — Albanian Lek",
        "֏ AMD — Armenian Dram",
        "ƒ ANG — Netherlands Antillean Guilder",
        "Kz AOA — Angolan Kwanza",
        "$ ARS — Argentine Peso",
        "A$ AUD — Australian Dollar",
        "ƒ AWG — Aruban Florin",
        "₼ AZN — Azerbaijani Manat",
        "KM BAM — Bosnia-Herzegovina Convertible Mark",
        "Bds$ BBD — Barbadian Dollar",
        "৳ BDT — Bangladeshi Taka",
        "лв BGN — Bulgarian Lev",
        "BHD BHD — Bahraini Dinar",
        "FBu BIF — Burundian Franc",
        "$ BMD — Bermudian Dollar",
        "B$ BND — Brunei Dollar",
        "Bs. BOB — Bolivian Boliviano",
        "R$ BRL — Brazilian Real",
        "B$ BSD — Bahamian Dollar",
        "Nu. BTN — Bhutanese Ngultrum",
        "P BWP — Botswana Pula",
        "Br BYN — Belarusian Ruble",
        "BZ$ BZD — Belize Dollar",
        "C$ CAD — Canadian Dollar",
        "FC CDF — Congolese Franc",
        "CHF CHF — Swiss Franc",
        "$ CLP — Chilean Peso",
        "¥ CNY — Chinese Yuan",
        "$ COP — Colombian Peso",
        "₡ CRC — Costa Rican Colón",
        "$ CUP — Cuban Peso",
        "$ CVE — Cape Verdean Escudo",
        "Kč CZK — Czech Koruna",
        "Fdj DJF — Djiboutian Franc",
        "kr. DKK — Danish Krone",
        "RD$ DOP — Dominican Peso",
        "دج DZD — Algerian Dinar",
        "E£ EGP — Egyptian Pound",
        "Nfk ERN — Eritrean Nakfa",
        "Br ETB — Ethiopian Birr",
        "€ EUR — Euro",
        "FJ$ FJD — Fijian Dollar",
        "£ FKP — Falkland Islands Pound",
        "£ GBP — British Pound Sterling",
        "₾ GEL — Georgian Lari",
        "₵ GHS — Ghanaian Cedi",
        "£ GIP — Gibraltar Pound",
        "D GMD — Gambian Dalasi",
        "FG GNF — Guinean Franc",
        "Q GTQ — Guatemalan Quetzal",
        "G$ GYD — Guyanese Dollar",
        "HK$ HKD — Hong Kong Dollar",
        "L HNL — Honduran Lempira",
        "G HTG — Haitian Gourde",
        "Ft HUF — Hungarian Forint",
        "Rp IDR — Indonesian Rupiah",
        "₪ ILS — Israeli New Shekel",
        "IQD IQD — Iraqi Dinar",
        "﷼ IRR — Iranian Rial",
        "kr ISK — Icelandic Króna",
        "J$ JMD — Jamaican Dollar",
        "JOD JOD — Jordanian Dinar",
        "¥ JPY — Japanese Yen",
        "KSh. KES — Kenyan Shilling",
        "с KGS — Kyrgyzstani Som",
        "៛ KHR — Cambodian Riel",
        "CF KMF — Comorian Franc",
        "₩ KPW — North Korean Won",
        "₩ KRW — South Korean Won",
        "KWD KWD — Kuwaiti Dinar",
        "CI$ KYD — Cayman Islands Dollar",
        "₸ KZT — Kazakhstani Tenge",
        "₭ LAK — Lao Kip",
        "ل.ل LBP — Lebanese Pound",
        "රු LKR — Sri Lankan Rupee",
        "L$ LRD — Liberian Dollar",
        "L LSL — Lesotho Loti",
        "LYD LYD — Libyan Dinar",
        "د.م. MAD — Moroccan Dirham",
        "L MDL — Moldovan Leu",
        "Ar MGA — Malagasy Ariary",
        "ден MKD — Macedonian Denar",
        "K MMK — Myanmar Kyat",
        "₮ MNT — Mongolian Tögrög",
        "MOP$ MOP — Macanese Pataca",
        "UM MRU — Mauritanian Ouguiya",
        "₨ MUR — Mauritian Rupee",
        "Rf MVR — Maldivian Rufiyaa",
        "MK MWK — Malawian Kwacha",
        "MX$ MXN — Mexican Peso",
        "RM. MYR — Malaysian Ringgit",
        "MT MZN — Mozambican Metical",
        "N$ NAD — Namibian Dollar",
        "₦ NGN — Nigerian Naira",
        "C$ NIO — Nicaraguan Córdoba",
        "kr NOK — Norwegian Krone",
        "Rs. NPR — Nepalese Rupee",
        "NZ$ NZD — New Zealand Dollar",
        "OMR. OMR — Omani Rial",
        "B/. PAB — Panamanian Balboa",
        "S/ PEN — Peruvian Sol",
        "K PGK — Papua New Guinean Kina",
        "₱ PHP — Philippine Peso",
        "Rs. PKR — Pakistani Rupee",
        "zł PLN — Polish Złoty",
        "₲ PYG — Paraguayan Guarani",
        "QAR. QAR — Qatari Riyal",
        "lei RON — Romanian Leu",
        "дин. RSD — Serbian Dinar",
        "₽ RUB — Russian Ruble",
        "FRw RWF — Rwandan Franc",
        "SAR. SAR — Saudi Riyal",
        "SI$ SBD — Solomon Islands Dollar",
        "₨ SCR — Seychellois Rupee",
        "ج.س. SDG — Sudanese Pound",
        "kr SEK — Swedish Krona",
        "S$ SGD — Singapore Dollar",
        "£ SHP — Saint Helena Pound",
        "Le SLE — Sierra Leonean Leone",
        "S SOS — Somali Shilling",
        "SR$ SRD — Surinamese Dollar",
        "£ SSP — South Sudanese Pound",
        "Db STN — São Tomé and Príncipe Dobra",
        "£ SYP — Syrian Pound",
        "E SZL — Eswatini Lilangeni",
        "฿ THB — Thai Baht",
        "SM TJS — Tajikistani Somoni",
        "T TMT — Turkmenistan Manat",
        "TND. TND — Tunisian Dinar",
        "T$ TOP — Tongan Paʻanga",
        "₺ TRY — Turkish Lira",
        "TT$ TTD — Trinidad and Tobago Dollar",
        "NT$ TWD — New Taiwan Dollar",
        "TSh TZS — Tanzanian Shilling",
        "₴ UAH — Ukrainian Hryvnia",
        "USh UGX — Ugandan Shilling",
        "$ USD — US Dollar",
        "$U UYU — Uruguayan Peso",
        "Bs.D VED — Venezuelan Digital Bolívar",
        "Bs.S VES — Venezuelan Bolívar",
        "₫ VND — Vietnamese Đồng",
        "VT VUV — Vanuatu Vatu",
        "T WST — Samoan Tala",
        "FCFA XAF — Central African CFA Franc",
        "EC$ XCD — East Caribbean Dollar",
        "FCFA XOF — West African CFA Franc",
        "₣ XPF — CFP Franc",
        "﷼ YER — Yemeni Rial",
        "R. ZAR — South African Rand",
        "ZK ZMW — Zambian Kwacha",
        "ZiG ZWG — Zimbabwe Gold",
    ];
}
